name: Compilar, Ejecutar y Publicar Blazor Cover Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --configuration Release

      #- name: Ejecutar pruebas (opcional)
        #run: dotnet test

      - name: Publicar aplicación
        run: dotnet publish --configuration Release --output ./publish

      - name: Configurar GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish

